POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The Man on the Moon",
    "author": "Alexander Sobschyzn",
    "url": "http://the-man-on-the-moon.org",
    "likes": 25
}

#####
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhMmZmN2UyOGQxNDRmYmViNDk4MDgwMCIsImlhdCI6MTc4MTUzNDI2MX0.CZGziTgH8a3PxFHfh95ZUIhNWoJTDDn3daBmKTftNFM


{
    "title": "How can you live like that",
    "author": "Andrea Solibini",
    "url": "http://how-can-you-live-like-that.org",
    "likes": 43
}

#####
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhMmZmN2UyOGQxNDRmYmViNDk4MDgwMCIsImlhdCI6MTc4MTUzNDI2MX0.CZGziTgH8a3PxFHfh95ZUIhNWoJTDDn3daBmKTftNFM

{
    "title": "And we continue to watch",
    "author": "Susi Boston",
    "url": "http://and-we-continue-to-watch.org",
    "likes": 3
}